site_name: 'Documentation Template'
repo_url: https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.account_name }}-{{ cookiecutter.project_slug }}
edit_uri: https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.account_name }}-{{ cookiecutter.project_slug }}/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core